// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jomhanuxtterobymntmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbWhhbnV4dHRlcm9ieW1udG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODc5ODUsImV4cCI6MjA2NDc2Mzk4NX0.7KMSMNyYS-e6f4ovOpXVmV3ywgNJyG9NNDKRqA3Qvgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);